plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle' version '7.0.152'
}

version = '1.21.1-9.0.0.0'
group = 'br.com.isageek.automata'

base {
    archivesName = 'automata'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

minecraft {
    mappings channel: 'official', version: '1.21.1'
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                automata {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                automata {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'automata', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            mods {
                automata {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://maven.neoforged.net/releases' }
    mavenCentral()
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    minecraft 'net.neoforged:neoforge:21.10.55-beta'

    testImplementation(
            'junit:junit:4.13.2',
            'org.mockito:mockito-core:3.12.4'
    )
}

jar {
    manifest {
        attributes([
            "Specification-Title": "automata",
            "Specification-Vendor": "automataCraft",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"automataCraft",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}
