# JVM configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod properties
mod_id=automata
mod_name=Automata
mod_group_id=br.com.isageek.automata
mod_version=1.21.10-9.0.0.0
mod_authors=Beothorn
mod_license=Apache License 2.0
mod_description=A minecraft mod that replaces programmable 3x3 block patterns with new blocks.

# Minecraft/NeoForge versions
minecraft_version=1.21.10
minecraft_version_range=[1.21.10,1.22)
neo_version=21.10.55-beta
neo_version_range=[21.10.55-beta,)

# Mappings
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1
